package com.huroofna.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 TextToSpeech tts; LinearLayout root,content; int stars=0; final String[] letters={"ا","ب","ت","ث","ج","ح","خ","د","ذ","ر","ز","س","ش","ص","ض","ط","ظ","ع","غ","ف","ق","ك","ل","م","ن","ه","و","ي"};
 final String[] words={"باب","بيت","ماما","موز","نار","سور","قلم","كتاب"}; final String[] sentences={"هذا باب.","ماما تقرأ.","أنا أحب المدرسة.","هذا قلم."};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);stars=getPreferences(0).getInt("stars",0);tts=new TextToSpeech(this,s->{});showHome();}
 TextView tv(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setGravity(Gravity.CENTER);v.setTextColor(Color.rgb(40,40,55));v.setPadding(12,16,12,16);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setAllCaps(false);b.setPadding(12,10,12,10);return b;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.setBackgroundColor(Color.rgb(250,249,246)); TextView h=tv(title,28);h.setTypeface(null,1);root.addView(h,new LinearLayout.LayoutParams(-1,-2));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void add(String s,int size){content.addView(tv(s,size),new LinearLayout.LayoutParams(-1,-2));}
 void nav(){Button back=btn("↩ العودة للرئيسية");back.setOnClickListener(v->showHome());root.addView(back,new LinearLayout.LayoutParams(-1,-2));}
 void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"h");}
 void showHome(){base("🌟 حروفنا");add("من الحرف إلى القراءة والكتابة",20);add("⭐ النجوم: "+stars,20);String[] ms={"🔤 الحروف والأصوات","َ ُ ِ الحركات والمد","🧩 الكلمات","📖 الجمل والفهم","🎮 لعبة تمييز الحرف","✍️ الكتابة بالإصبع","📝 الاختبار التشخيصي","📊 تقدمي"};for(String m:ms){Button b=btn(m);content.addView(b);if(m.startsWith("🔤"))b.setOnClickListener(v->letters());else if(m.startsWith("َ"))b.setOnClickListener(v->harakat());else if(m.startsWith("🧩"))b.setOnClickListener(v->words());else if(m.startsWith("📖"))b.setOnClickListener(v->sentences());else if(m.startsWith("🎮"))b.setOnClickListener(v->game());else if(m.startsWith("✍"))b.setOnClickListener(v->writing());else if(m.startsWith("📝"))b.setOnClickListener(v->test());else b.setOnClickListener(v->progress());}}
 void letters(){base("الحروف الهجائية");add("اضغط على الحرف لسماع صوته",18);GridLayout g=new GridLayout(this);g.setColumnCount(4);for(String l:letters){Button b=btn(l);b.setTextSize(30);b.setOnClickListener(v->{speak(l);addStar();showLetter(l);});g.addView(b,new ViewGroup.LayoutParams(0,110));}content.addView(g);nav();}
 void showLetter(String l){base("حرف "+l);add(l,72);add("اسم الحرف: "+l,22);add("أشكال الحرف للتدريب",18);add(l+"ـ   ـ"+l+"   "+l,30);Button s=btn("🔊 اسمع");s.setOnClickListener(v->speak(l));content.addView(s);add("الحركات: "+l+"َ   "+l+"ُ   "+l+"ِ",28);add("المد: "+l+"ا   "+l+"و   "+l+"ي",28);nav();}
 void harakat(){base("الحركات والمد");add("فتحة  َ   ضمة  ُ   كسرة  ِ",30);for(String l:new String[]{"ب","م","س","ن"})add(l+"َ   "+l+"ُ   "+l+"ِ     |     "+l+"ا   "+l+"و   "+l+"ي",28);Button b=btn("🔊 اسمع التدريب");b.setOnClickListener(v->speak("بَ بُ بِ با بو بي"));content.addView(b);nav();}
 void words(){base("الكلمات");add("اقرأ الكلمة ثم اسمعها",20);for(String w:words){Button b=btn("🔊 "+w);b.setTextSize(25);b.setOnClickListener(v->{speak(w);addStar();});content.addView(b);}nav();}
 void sentences(){base("الجمل والفهم");for(String s:sentences){add("📖 "+s,25);Button b=btn("🔊 اسمع الجملة");b.setOnClickListener(v->speak(s));content.addView(b);add("سؤال: هل قرأت الجملة؟  نعم / أحاول مرة أخرى",17);}nav();}
 void game(){base("🎮 لعبة تمييز الحرف");Random r=new Random();String target=letters[r.nextInt(letters.length)];add("اختر الحرف:  "+target,32);ArrayList<String> opts=new ArrayList<>();opts.add(target);while(opts.size()<4){String x=letters[r.nextInt(letters.length)];if(!opts.contains(x))opts.add(x);}Collections.shuffle(opts);for(String x:opts){Button b=btn(x);b.setTextSize(30);b.setOnClickListener(v->{if(((Button)v).getText().toString().equals(target)){addStar();Toast.makeText(this,"أحسنت! ⭐",Toast.LENGTH_SHORT).show();}else Toast.makeText(this,"حاول مرة أخرى",Toast.LENGTH_SHORT).show();});content.addView(b);}nav();}
 void writing(){base("✍️ أكتب الحرف");add("اكتب بإصبعك داخل المربع",18);DrawView d=new DrawView();content.addView(d,new LinearLayout.LayoutParams(-1,520));Button clear=btn("مسح");clear.setOnClickListener(v->{d.clear();});content.addView(clear);Button done=btn("أنهيت التدريب ⭐");done.setOnClickListener(v->{addStar();Toast.makeText(this,"رائع!",Toast.LENGTH_SHORT).show();});content.addView(done);nav();}
 void test(){base("📝 الاختبار التشخيصي");add("1) اختر حرف (ب):",22);for(String x:new String[]{"ب","ت","ن"}){Button b=btn(x);b.setOnClickListener(v->{if(x.equals("ب")){addStar();Toast.makeText(this,"صحيح ⭐",Toast.LENGTH_SHORT).show();}});content.addView(b);}add("2) اقرأ: باب",22);add("3) اختر الحركة الصحيحة: بَ",22);Button ok=btn("✓ أنهيت الاختبار");ok.setOnClickListener(v->{addStar();Toast.makeText(this,"تم تسجيل التقدم",Toast.LENGTH_SHORT).show();});content.addView(ok);nav();}
 void progress(){base("📊 تقدمي");add("النجوم الحالية: ⭐ "+stars,28);add("تقدمك محفوظ على هذا الهاتف.",19);add("لتحسين القراءة: كرر الحروف ثم الحركات ثم الكلمات والجمل.",19);nav();}
 void addStar(){stars++;getPreferences(0).edit().putInt("stars",stars).apply();}
 class DrawView extends View{Paint p=new Paint();Path path=new Path();DrawView(){super(MainActivity.this);p.setStrokeWidth(10);p.setStyle(Paint.Style.STROKE);p.setColor(Color.DKGRAY);setBackgroundColor(Color.WHITE);}protected void onDraw(Canvas c){c.drawPath(path,p);}public boolean onTouchEvent(android.view.MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==0)path.moveTo(x,y);else if(e.getAction()==2)path.lineTo(x,y);invalidate();return true;}void clear(){path.reset();invalidate();}}
 @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
